# Generated by Django 2.1.dev20180503134330 on 2018-05-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=120)),
                ('order', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
